create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 1 and 6),
  lesson_number smallint not null check (lesson_number > 0),
  subject_name text not null,
  time_start time not null,
  time_end time not null,
  constraint schedule_time_order check (time_start < time_end)
);

create index if not exists schedule_group_day_idx
  on public.schedule (group_id, day_of_week, lesson_number);

alter table public.groups enable row level security;
alter table public.schedule enable row level security;

create policy "Public groups are readable"
  on public.groups for select
  using (true);

create policy "Public schedule is readable"
  on public.schedule for select
  using (true);

insert into public.groups (id, name) values
  (1, 'ВЕБ-21'),
  (2, 'ИС-22')
on conflict (id) do update set name = excluded.name;

insert into public.schedule
  (id, group_id, day_of_week, lesson_number, subject_name, time_start, time_end)
values
  (1, 1, 1, 1, 'Веб-разработка', '08:30', '09:50'),
  (2, 1, 1, 2, 'JavaScript', '09:55', '11:15'),
  (3, 1, 2, 1, 'Базы данных', '08:30', '09:50'),
  (4, 1, 2, 2, 'UI/UX', '09:55', '11:15'),
  (5, 1, 3, 1, 'Node.js', '08:30', '09:50'),
  (6, 1, 3, 2, 'Supabase', '09:55', '11:15'),
  (7, 1, 4, 1, 'Проектирование API', '08:30', '09:50'),
  (8, 1, 4, 2, 'Git и GitHub', '09:55', '11:15'),
  (9, 1, 5, 1, 'Тестирование', '08:30', '09:50'),
  (10, 1, 5, 2, 'Деплой на Vercel', '09:55', '11:15'),
  (11, 2, 1, 1, 'Информационные системы', '08:30', '09:50'),
  (12, 2, 1, 2, 'Алгоритмы', '09:55', '11:15'),
  (13, 2, 2, 1, 'Python', '08:30', '09:50'),
  (14, 2, 2, 2, 'SQL', '09:55', '11:15'),
  (15, 2, 3, 1, 'Сетевые технологии', '08:30', '09:50'),
  (16, 2, 4, 1, 'Кибербезопасность', '08:30', '09:50'),
  (17, 2, 5, 1, 'DevOps', '08:30', '09:50'),
  (18, 2, 5, 2, 'Проектная практика', '09:55', '11:15')
on conflict (id) do update set
  group_id = excluded.group_id,
  day_of_week = excluded.day_of_week,
  lesson_number = excluded.lesson_number,
  subject_name = excluded.subject_name,
  time_start = excluded.time_start,
  time_end = excluded.time_end;
